POST http://localhost:8080/api/users/1/trainings/19/sets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNTYwMzc5NTMzLCJleHAiOjE1NjA5ODQzMzN9.m48po18bxorukrBEkGaUs6lq-QNgYsuZJhXnExkkbev6S9FYa2PkA7JjY_UDbpmXnz6FV8ho4NyUakXXr-Uy1g

{
  "exerciseId": 1,
  "reps": 10,
  "weightInKg": 10,
  "calories": 100,
  "durationInMinutes": 5,
  "distanceInKm": 1,
  "additionalInfo": "Test"
}

###