POST http://localhost:8080/api/auth/signup
Content-Type: application/json

{
  "firstName": "Aleksander",
  "lastName": "Kołata",
  "username": "olek.tbg",
  "email": "olek.tbg@gmail.com",
  "password": "password"
}

###